import { debug } from "@actions/core";
import { Context } from "@actions/github/lib/context";
import type { GitHub } from "@actions/github/lib/utils";
import { config, cosmic } from "@anandchowdhary/cosmic";
import { BookResult } from "../google-books";
import { updateSummary } from "./update-summary";

export const onIssueComment = async (
  owner: string,
  repo: string,
  context: Context,
  octokit: InstanceType<typeof GitHub>
) => {
  debug("Started onIssueComment");
  try {
    await cosmic("bookshelf");
    debug("Got config object");
  } catch (error) {}
  const issue = await octokit.rest.issues.get({
    owner: context.issue.owner,
    repo: context.issue.repo,
    issue_number: context.issue.number,
  });
  debug(`Got issue #${issue.data.number}`);
  if (config("users") && Array.isArray(config("users"))) {
    if (!(config("users") as string[]).find((i) => (issue.data.user || {}).login))
      return debug("User not allowed, skipping");
  }
  if (
    !issue.data.labels.find((i) =>
      typeof i === "string" ? i === "kind: book" : i.name === "kind: book"
    )
  )
    return debug('Issue not of "kind: book", skipping');

  const comments = await octokit.rest.issues.listComments({
    owner: context.issue.owner,
    repo: context.issue.repo,
    issue_number: context.issue.number,
  });
  debug(`Got ${comments.data.length} comments in issue`);
  if (comments.data.length < 2) return debug("Less than 2 comments, skipping");

  // Skip autogenerated comments
  const lastComment = comments.data.sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  )[0];
  if (!lastComment) throw new Error("Last comment not found");
  if ((lastComment.body || "").includes("This comment is autogenerated"))
    return debug("Comment was autogenerated, skipping");

  debug(`Found last comment #${lastComment.id}: "${lastComment.body}"`);
  const commentBody = (lastComment.body || "").trim();

  // --- Handle category: command ---
  // Format: "category:favorites,2025" or "category: favorites, 2026"
  const categoryMatch = commentBody.match(/^category:\s*(.+)$/im);
  if (categoryMatch) {
    const categories = categoryMatch[1].split(",").map((c) => c.trim()).filter(Boolean);
    debug(`Parsed categories: ${categories.join(", ")}`);

    // Add category labels
    const categoryLabels = categories.map((c) => `category: ${c}`);
    await octokit.rest.issues.addLabels({
      owner: context.issue.owner,
      repo: context.issue.repo,
      issue_number: context.issue.number,
      labels: categoryLabels,
    });
    debug("Added category labels");

    // React to confirm
    try {
      await octokit.rest.reactions.createForIssueComment({
        owner: context.issue.owner,
        repo: context.issue.repo,
        issue_number: context.issue.number,
        comment_id: lastComment.id,
        content: "+1",
      });
    } catch (error) {}

    await updateSummary(owner, repo, context, octokit);
    return;
  }

  // --- Handle rating: command ---
  // Format: "rating:4.5" or "rating: 4/5" or "rating: 4.5/5"
  const ratingMatch = commentBody.match(/^rating:\s*([\d.]+)\s*(?:\/\s*5)?$/im);
  if (ratingMatch) {
    const rating = parseFloat(ratingMatch[1]);
    if (!isNaN(rating) && rating >= 0 && rating <= 5) {
      debug(`Parsed rating: ${rating}/5`);

      // Remove existing rating labels
      const existingLabels = issue.data.labels
        .map((l) => (typeof l === "string" ? l : l.name || ""))
        .filter((l) => l.startsWith("rating:"));
      for (const label of existingLabels) {
        try {
          await octokit.rest.issues.removeLabel({
            owner: context.issue.owner,
            repo: context.issue.repo,
            issue_number: context.issue.number,
            name: label,
          });
        } catch (error) {}
      }

      // Add new rating label
      const ratingLabel = `rating: ${rating}/5`;
      await octokit.rest.issues.addLabels({
        owner: context.issue.owner,
        repo: context.issue.repo,
        issue_number: context.issue.number,
        labels: [ratingLabel],
      });
      debug("Added rating label");

      // React to confirm
      try {
        await octokit.rest.reactions.createForIssueComment({
          owner: context.issue.owner,
          repo: context.issue.repo,
          issue_number: context.issue.number,
          comment_id: lastComment.id,
          content: "+1",
        });
      } catch (error) {}

      await updateSummary(owner, repo, context, octokit);
      return;
    }
  }

  // --- Handle progress (original behavior) ---
  let json: BookResult | undefined = undefined;
  try {
    comments.data.forEach((comment: any) => {
      if ((comment.body || "").includes("Book details (JSON)"))
        json = JSON.parse((comment.body || "").split("```json")[1].split("```")[0]) as BookResult;
    });
  } catch (error) {
    console.log("JSON parsing error", error);
  }
  debug("Got JSON data for book");
  if (json) debug(`Total pages in JSON are ${(json as BookResult).pageCount}`);

  let progressPercent = 0;
  let totalPages = json ? (json as BookResult).pageCount : 1;
  if (commentBody.includes("/")) {
    debug("Last comment includes slash so must have length");
    const num = commentBody.split("/")[1].match(/\d+/g);
    if (num && num.length) {
      const potentialPages = parseInt(num[0]);
      if (!isNaN(potentialPages) && potentialPages) {
        totalPages = potentialPages;
      }
    }
  }
  debug(`Total pages in book are ${totalPages}`);
  const valuesInComment = commentBody.match(/\d+\%?/g);
  if (valuesInComment && valuesInComment.length) {
    const values = valuesInComment.map((val: string) => parseInt(val)).filter((val: number) => !isNaN(val));
    const firstVal = valuesInComment[0];
    if (values.length)
      if (firstVal.includes("%") && !isNaN(parseInt(firstVal))) {
        progressPercent = parseInt(firstVal);
      } else {
        progressPercent = Math.min(Math.round((100 * values[0]) / totalPages), 100);
      }
  }
  debug(`Progress is ${progressPercent}%`);
  if (progressPercent !== 0) {
    try {
      await octokit.rest.reactions.createForIssueComment({
        owner: context.issue.owner,
        repo: context.issue.repo,
        issue_number: context.issue.number,
        comment_id: lastComment.id,
        content: "+1",
      });
    } catch (error) {}
    const currentPercentage = issue.data.title.match(/\(\d+\%\)/g);
    await octokit.rest.issues.update({
      owner: context.issue.owner,
      repo: context.issue.repo,
      issue_number: context.issue.number,
      title:
        currentPercentage && currentPercentage.length
          ? `${issue.data.title.split(currentPercentage[0])[0].trim()} (${progressPercent}%)`
          : `${issue.data.title.trim()} (${progressPercent}%)`,
    });
    debug("Updated issue title with progress");
    // Remove "want to read" label if it's there
    if (
      issue.data.labels.find((i) =>
        typeof i === "string" ? i === "want to read" : i.name === "want to read"
      )
    ) {
      try {
        await octokit.rest.issues.removeLabel({
          owner: context.issue.owner,
          repo: context.issue.repo,
          issue_number: context.issue.number,
          name: "want to read",
        });
      } catch (error) {}
    }
  }
  await updateSummary(owner, repo, context, octokit);
};
